apiVersion: 1

deleteDatasources:
  - name: Tempo
    orgId: 1
  - name: Mimir
    orgId: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true

  - name: Mimir
    uid: mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
